site_name: ckan_uploader

pages:
    - Home: index.md
    - Desarrollo: development.md
    - Produccion: production.md
    - creditos: credits.md

theme: readthedocs
repo_url: https://github.com/datosgobar/ckan_uploader
site_author: Jose A. Salgado

extra:
    version: 1.0